### ISSUE TITLE
UnhandledPromiseRejectionWarning when using

### ISSUE THREAD

**Issue by lucasz-hu** [gafotech/sochain#4]
I'm just trying out the demo code and I'm getting returned the HTML of the URL

This was my code`var SoChain = require('sochain');

var chain = new SoChain('BTC'); // see below for possible networks
`
chain.block(530000).then(console.log);
`

and then this was the error:
`(node:5460) UnhandledPromiseRejectionWarning: Error: <!DOCTYPE HTML>
HTML OF SITE GOES HERE, I took it out because of too much space
   at Request.request [as _callback] (c:\Users\Lucas\node_modules\sochain\index.js:27:18)
    at Request.self.callback (c:\Users\Lucas\node_modules\request\request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (c:\Users\Lucas\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (c:\Users\Lucas\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
`

**Comment by thegafo** [comment]
@lucasz-hu Thanks for trying out the library. I just tried to reproduce your bug but was unable -- it seems to be working now.

Please note that [SoChain](https://sochain.com/) is an online service (that I have no affiliation with) and this library simply uses its publicly available API. Downtime and rate-limiting are definitely possible.
